config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,   only: [:edit, :index, :show, :destroy]
  resources :books
  resources :autors,   only: [:new, :create]
  resources :comments, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  root                'static_page#home'

  get 'about'    =>   'static_page#about'

  get 'set_admin' => 'users#set_destroy_admin'
  get 'add_book'  => 'users#add_book'
  get 'moder_comment' => 'users#all_comment_moderation'
  get 'moderation'  => 'users#moderation'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :interim_tables
    has_many :users, through: :interim_tables
    belongs_to :autor
    has_many :comments
    mount_uploader :picture, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :book
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    validates :info, presence: true, length: { maximum: 140 }

    def moder
        update_attribute(:activ, true)
    end
end

app/models/interim_table.rb
class InterimTable < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :interim_tables
  has_many :comments
  has_many :books, through: :interim_tables

  def set_admin
    update_attribute(:admin,    true)
  end

  def del_admin
    update_attribute(:admin,    false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
    before_action :admin_user,     only: [:new, :create]
    def index
    end
    def new
        @autor = Autor.new
    end
    def create
        @autor = Autor.new(autor_params)
        if @autor.save
          flash[:info] = "Autor create!"
          redirect_to root_url
        else
          render 'new'
        end
    end
    private
    def autor_params
        params.require(:autor).permit(:second_name, :first_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :admin_user,     only: [:destroy]
  before_action :authenticate_user!,   only: [:show, :index]

  def show
    @book = Book.find(params[:id])
    @autor = @book.autor
    @comments = @book.comments.where(activ: true)
    @comment = current_user.comments.build
  end
  
  def new
    @book=Book.new
    @autors = Autor.all
  end

  def create
    @book = Book.new(book_params)
    @book.autor_id=params[:autor_id]
        if @book.save
          flash[:info] = "Book create!"
          redirect_to root_url
        else
          render 'new'
        end
  end

  def index
    @books = Book.page(params[:page]).per(12)
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to home_url
  end

  private
  def book_params
    params.require(:book).permit(:name,:picture,:description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: [:destroy]

  def index
    @user = current_user
    @comments = @user.comments.where(activ: true).page(params[:page]).per(10)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.book_id = params[:book_id]
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @book = @comment.book
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.activ = false
    if @comment.update_attributes(comment_params)
      flash[:success] = "Comment updated"
      redirect_to comments_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to request.referrer || root_url
  end

  private

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end

    def comment_params
      params.require(:comment).permit(:info)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
   
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed, only: [:destroy, :show, :index, :update, :add_book]
  before_action :admin_user,      only: [:destroy, :show, :index, :update,:set_destroy_admin]

  def show
    @user = User.find(params[:id])
    #debugger
    @books = @user.books  
  end

  def index
    @users = User.page(params[:page]).per(10)
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def all_comment_moderation
    @comments = Comment.where(activ:false).page(params[:page]).per(15)
  end

  def moderation
    @comment = Comment.find(params[:id])
    @comment.moder;
    redirect_back(fallback_location: root_path)
  end

  def add_book
    @book = Book.find(params[:id])
    if (InterimTable.where(book_id:@book.id, user_id:current_user.id).empty?)
      InterimTable.create!(book_id:@book.id, user_id:current_user.id)
    else
      InterimTable.find_by(book_id:@book.id,user_id:current_user.id).destroy
    end
    redirect_back(fallback_location: root_path)
  end

  def set_destroy_admin
    @user = User.find(params[:id])
    if (@user.admin?)
      @user.del_admin
    else 
      @user.set_admin
    end
    redirect_to users_url
  end

  private

    def user_signed
      redirect_to(root_url) unless user_signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper

end

app/helpers/users_helper.rb
module UsersHelper
    # Возвращает граватар для данного пользователя.
    def gravatar_for(user, options = { size: 80 })
    #debugger
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/autors/new.html.erb
<% provide(:title, 'Add Autor') %>
<h1>Add Autor</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@autor) do |f|%>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
      <%= f.label :second_name %>
      <%= f.text_field :second_name, class: 'form-control' %>
      <%= f.submit "Create Autor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>  

app/views/books/_book.html.erb
<div class="col-sm-6 col-md-3 col-lg-3">
    <div class="thumbnail">
    <img class="picture" src=<%= book.picture %> alt="Picture" >
        <div class="caption">
            <h2><%= book.name %></h2>
            <p class="book"><%= book.autor.first_name %> <%= book.autor.second_name %></p>
            <div class="row">
                <%= link_to "Button", {:controller => "books", :action => "show", :id => book.id },
                                                             class: "btn btn-primary col-md-6"%>
                <% if(InterimTable.where(book_id:book.id, user_id:current_user.id).empty?) %>
                    <%= link_to "+", {:controller => "users", :action => "add_book", :id => book.id }, 
                                                        class: "btn btn-primary col-md-6"%>      
                <% else %>
                    <%= link_to "-", {:controller => "users", :action => "add_book", :id => book.id }, 
                                                        class: "btn btn-primary col-md-6"%>   
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="row">
    <% @books.each do |book| %>
    <%= render book %>
    <% end %>
</div>


<%= paginate @books %>
<%= page_entries_info @books %>

app/views/books/new.html.erb
<% provide(:title, 'Add book') %>
<h1>Add book</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f|%>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <select name="autor_id" id="autor_id">
        <% @autors.each do |autor| %>
          <option value=<%=autor.id%>><%=autor.first_name%> <%=autor.second_name%></option>
        <% end %>
      </select>
      <%= f.label :picture %>
      <%= f.file_field :picture %>
      <%= f.label :description, "Confirmation" %>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.submit "Create book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>  

app/views/books/show.html.erb
<% provide(:title, @book.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
        <%= image_tag @book.picture, size: "360x500" %>
    </section>
  </aside>
  <div class="col-md-8">
      <h1>     
         <%= @book.name %>
      </h1>
      <h3>Autor: <%= @autor.first_name%> <%= @autor.second_name%></h3>
      <h3>Description this (<%= @book.name %>)</h3>
      <%= @book.description %>
  </div>
  <div class="col-md-8">
    <% if @book.comments.any? %>
      <h3>Comments (<%= @book.comments.count %>)</h3>
      <ol class="microposts">
        <% @comments.each do |comment|%>
          <%= render comment %>
        <% end %>
      </ol>
    <% end %>
  </div>
  <div class="micropost_form">
      <%= render 'shared/comment_form' %>
  </div>
</div>

app/views/comments/_comment.html.erb
<li id="micropost-<%= comment.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user%>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <br/>
  <span class="content">
    <%= comment.info %>
  </span>
  <br/>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
    <% if current_user.id == comment.user_id %>
      | <%= link_to "delete", comment, method: :delete,
                              data: { confirm: "You sure?" } %>
      | <%= link_to "change", edit_comment_path(comment.id)%>
    <% end %>
  </span>
</li>

app/views/comments/edit.html.erb
<% provide(:title, "Edit user") %>
<%= form_for(@comment) do |f| %>
    <div class="field">
      <%= f.text_area :info, placeholder: "Compose new comment..." %>
      <input type="number" name="book_id" value=<%= @book.id %> readonly>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/comments/index.html.erb
<% provide(:title, 'All comments') %>
<h1>All comments</h1>

<ul class="users">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</ul>

<%= paginate @comments %>
<%= page_entries_info @comments %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li> 
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <% if(user_signed_in? && current_user.admin?)%>
              <li><%= link_to "Users", users_path %></li>
              <% end %>
              <li><%= link_to "Comment", comments_path %></li>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Add <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Book", new_book_path %></li>
              <li><%= link_to "Autor", new_autor_path %></li>
              <li><%= link_to "Moderation Comment", moder_comment_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
    <div class="field">
      <%= f.text_area :info, placeholder: "Compose new comment..." %>
      <input type="number" name="book_id" value=<%= @book.id %> readonly>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/about.html.erb
<h1>StaticPage#about</h1>
<p>Find me in app/views/static_page/about.html.erb</p>

app/views/static_page/home.html.erb
<% if user_signed_in? %> 
    <%= controller.redirect_to books_path%>
<% else %>
    <div class="center jumbotron">
    <h1>Welcome to the Bookshelf</h1>
    <h2>
    This is the home page.
    </h2>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && user_signed_in? %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% if current_user != user %>
      <% if user.admin?%>
        | <%= link_to "delete admin routes", {:controller => "users", :action => "set_destroy_admin", :id => user.id },
                                      data: { confirm: "You sure?" } %>
      <% else %>
        | <%= link_to "set admin", {:controller => "users", :action => "set_destroy_admin", :id => user.id },
                                      data: { confirm: "You sure?" } %>
      <% end %>
    <% end %>
  <% end %>
</li>

app/views/users/all_comment_moderation.html.erb
<% provide(:title, 'All comments') %>
<h1>All comments</h1>

<ul class="users">
  <% @comments.each do |comment| %>
    <li id="micropost-<%= comment.id %>">
    <%= link_to gravatar_for(comment.user, size: 50), comment.user%>
    <span class="user"><%= link_to comment.user.name, comment.user %></span>
    <br/>
    <span class="content">
        <%= comment.info %>
    </span>
    <br/>
    <span class="timestamp">
        Posted <%= time_ago_in_words(comment.created_at) %> ago.
        <% if current_user.admin? %>
        | <%= link_to "delete", comment, method: :delete,
                                data: { confirm: "You sure?" } %>
        | <%= link_to "moderation", {:controller => "users",
                                :action => "moderation", :id => comment.id }%>
        <% end %>
    </span>
    </li>
  <% end %>
</ul>
    
<%= paginate @comments %>
<%= page_entries_info @comments %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= paginate @users %>
<%= page_entries_info @users %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<div class="row">
  <% @books.each do |book| %>
  <%= render book %>
  <% end %>
</div>